'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const C=['#ff5f91','#4eeaff','#ffd166','#8f7dff','#64f5aa','#ff8c5a','#a4ff5a','#ff6b6b'];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const rid=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const id=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const pick=a=>a[Math.floor(Math.random()*a.length)],shuffle=a=>[...a].sort(()=>Math.random()-.5);
const nodes=[{id:0,n:'王冠の間',x:.5,y:.5,adj:[1,2,3,4,5,6]},{id:1,n:'北門',x:.5,y:.2,adj:[0,2,6,7]},{id:2,n:'星見台',x:.75,y:.32,adj:[0,1,3,8]},{id:3,n:'東庭',x:.78,y:.62,adj:[0,2,4,9]},{id:4,n:'南門',x:.5,y:.8,adj:[0,3,5,10]},{id:5,n:'影路',x:.22,y:.62,adj:[0,4,6,11]},{id:6,n:'西庭',x:.25,y:.32,adj:[0,5,1,12]},{id:7,n:'高塔',x:.5,y:.07,adj:[1]},{id:8,n:'光橋',x:.94,y:.27,adj:[2]},{id:9,n:'決闘場',x:.94,y:.72,adj:[3]},{id:10,n:'地下王庫',x:.5,y:.95,adj:[4]},{id:11,n:'迷い森',x:.06,y:.72,adj:[5]},{id:12,n:'古代門',x:.06,y:.27,adj:[6]}];
const tactics={strike:{icon:'⚔️',name:'ストライク',desc:'同じ場所の1人へ2ダメージ'},guard:{icon:'🛡️',name:'ガード',desc:'被ダメージ-2。防げば+1'},snatch:{icon:'🫳',name:'スナッチ',desc:'同じ場所の1人から1点奪う'},burst:{icon:'💣',name:'バースト',desc:'同じ場所の全員へ1ダメージ'},feint:{icon:'🎭',name:'フェイント',desc:'攻撃後に移動する'}};
const rules=[{id:'normal',icon:'👑',name:'通常ルール',d:'王冠を奪え'},{id:'doubleCrown',icon:'✨',name:'黄金の王冠',d:'中央の得点が2倍'},{id:'fog',icon:'🌫️',name:'濃霧',d:'移動先の表示が遅れる'},{id:'bloodMoon',icon:'🌙',name:'血の月',d:'攻撃ダメージ+1'},{id:'festival',icon:'🎉',name:'祭典',d:'注目エリアの得点+2'},{id:'peace',icon:'🕊️',name:'休戦協定',d:'攻撃不可、得点勝負'}];
let peer=null,conns=new Map(),hostConn=null,me={id:id(),name:'',role:'player'},isHost=false,room='',state=null,selectedMove=null,selectedTactic=null,selectedTarget=null,timer=null,audio=true,lastReact=0;
const screens=['home','lobby','game','result'];
function show(n){screens.forEach(x=>$('#'+x+'Screen').classList.toggle('active',x===n))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function setOnline(v,t=v?'接続中':'未接続'){const p=$('#connectionPill');p.classList.toggle('online',v);p.classList.toggle('offline',!v);p.querySelector('span').textContent=t}
function beep(f=440,d=.08){if(!audio)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.05;o.connect(g).connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch{}}
function player(name,bot=false){return{id:id(),name,bot,role:'player',color:C[(state?.players?.length||0)%C.length],hp:5,score:0,node:Math.floor(Math.random()*6)+1,action:null,locked:false}}
function freshState(o={}){return{phase:'lobby',round:0,maxRounds:+o.maxRounds||8,turnSeconds:+o.turnSeconds||20,winScore:+o.winScore||14,maxPlayers:+o.maxPlayers||6,players:[],spectators:[],rule:rules[0],nextRuleOptions:[],votes:{},predictions:{},spotlight:7,log:'王冠を奪い合え！',endsAt:0}}
function snapshot(){return JSON.parse(JSON.stringify(state))}function send(c,m){try{c?.open&&c.send(m)}catch{}}function broadcast(m){conns.forEach(c=>send(c,m))}function sync(){if(!isHost)return;broadcast({type:'state',state:snapshot()});render()}
function createRoom(){me.name=($('#hostName').value||'ホスト').trim().slice(0,12);isHost=true;document.body.classList.add('is-host');state=freshState({maxPlayers:$('#maxPlayers').value,maxRounds:$('#maxRounds').value,turnSeconds:$('#turnSeconds').value,winScore:$('#winScore').value});const p=player(me.name);p.id=me.id;p.host=true;state.players.push(p);room=rid();peer=new Peer('crown-'+room.toLowerCase());peer.on('open',()=>{setOnline(true,'ホスト接続');enterLobby()});peer.on('connection',c=>{conns.set(c.peer,c);c.on('data',m=>hostMessage(c,m));c.on('close',()=>disconnect(c.peer));send(c,{type:'hello',room})});peer.on('error',()=>toast('接続エラー。もう一度試してね'))}
function joinRoom(){me.name=($('#joinName').value||'参加者').trim().slice(0,12);me.role=$('.role.active').dataset.role;room=$('#roomCodeInput').value.trim().toUpperCase();if(room.length<4){$('#joinError').textContent='ルームコードを入力してね';return}isHost=false;peer=new Peer();peer.on('open',()=>{hostConn=peer.connect('crown-'+room.toLowerCase(),{reliable:true});hostConn.on('open',()=>{setOnline(true,'接続済み');send(hostConn,{type:'join',user:me})});hostConn.on('data',clientMessage);hostConn.on('close',()=>{setOnline(false,'切断');toast('ホストとの接続が切れました')})});peer.on('error',()=>$('#joinError').textContent='部屋が見つからないか、接続できませんでした')}
function hostMessage(c,m){if(!m?.type)return;if(m.type==='join'){if(state.phase!=='lobby'&&m.user.role==='player')m.user.role='spectator';if(m.user.role==='player'&&state.players.length<state.maxPlayers){const p=player(m.user.name);p.id=m.user.id;p.conn=c.peer;state.players.push(p)}else state.spectators.push({id:m.user.id,name:m.user.name,conn:c.peer,role:'spectator',hype:0});send(c,{type:'joined',state:snapshot(),self:m.user.id});sync()}else if(m.type==='action'){const p=state.players.find(x=>x.id===m.id);if(p&&state.phase==='choose'){p.action=m.action;p.locked=true;sync();checkReady()}}else if(m.type==='unlock'){const p=state.players.find(x=>x.id===m.id);if(p&&state.phase==='choose'){p.action=null;p.locked=false;sync()}}else if(m.type==='vote'){state.votes[m.id]=m.rule;sync()}else if(m.type==='predict'){state.predictions[m.id]=m.player;sync()}else if(m.type==='react'){broadcast(m);floatReact(m.emoji)}}
function clientMessage(m){if(m.type==='state'){state=m.state;render()}else if(m.type==='joined'){state=m.state;me.id=m.self;show(state.phase==='lobby'?'lobby':'game');render()}else if(m.type==='react')floatReact(m.emoji)}
function disconnect(cid){conns.delete(cid);const p=state.players.find(x=>x.conn===cid);if(p){p.bot=true;p.conn=null;p.name+=' CPU';state.log=`${p.name} はCPUが引き継ぎました`}state.spectators=state.spectators.filter(x=>x.conn!==cid);sync()}
function enterLobby(){show('lobby');$('#roomCodeDisplay').textContent=room;history.replaceState(null,'',location.pathname+'?room='+room);drawQR(location.href);renderLobby()}
function addBot(){if(state.players.length>=state.maxPlayers)return;const n=['ノヴァ','ミント','クロウ','ルナ','ガンマ','ポン太','シロ','レイ'];state.players.push(player(n[state.players.length%n.length],true));sync()}
function startGame(){if(!isHost||state.players.length<2)return;state.phase='choose';state.round=1;state.rule=rules[0];state.spotlight=7;resetRound();show('game');sync();startClock()}
function resetRound(){state.players.forEach(p=>{p.locked=false;p.action=null;if(p.hp<=0){p.hp=5;p.node=Math.floor(Math.random()*6)+1}});state.nextRuleOptions=shuffle(rules.slice(1)).slice(0,3);state.votes={};state.predictions={};state.endsAt=Date.now()+state.turnSeconds*1000;selectedMove=selectedTactic=selectedTarget=null;botThink()}
function botThink(){state.players.filter(p=>p.bot).forEach((p,i)=>setTimeout(()=>{if(state.phase!=='choose'||p.locked)return;const ch=[p.node,...nodes[p.node].adj],target=[...state.players].filter(x=>x.id!==p.id).sort((a,b)=>b.score-a.score)[0];let move=Math.random()<.58?(p.node===0?0:(nodes[p.node].adj.includes(0)?0:pick(ch))):pick(ch),tactic=pick(Object.keys(tactics));if(state.rule.id==='peace'&&['strike','burst'].includes(tactic))tactic='guard';p.action={move,tactic,target:target?.id};p.locked=true;sync();checkReady()},500+i*250+Math.random()*1200))}
function startClock(){clearInterval(timer);timer=setInterval(()=>{if(!state||state.phase!=='choose')return;const l=Math.max(0,Math.ceil((state.endsAt-Date.now())/1000));$('#timerText').textContent=l;$('#timerRing').style.background=`conic-gradient(var(--cyan) ${l/state.turnSeconds*100}%,rgba(255,255,255,.08) 0)`;if(isHost&&l<=0)resolveRound()},250)}function checkReady(){if(isHost&&state.players.every(p=>p.locked))setTimeout(resolveRound,550)}
function damage(t,n,logs){let d=n;if(t.action?.tactic==='guard'){d=Math.max(0,n-2);if(d<n){t.score++;logs.push(`${t.name} がガード成功 +1`)}}t.hp-=d;if(d)beep(120,.05)}
function resolveRound(){if(!isHost||state.phase!=='choose')return;state.phase='reveal';clearInterval(timer);state.players.forEach(p=>{if(!p.action)p.action={move:p.node,tactic:'guard',target:null}});sync();beep(220,.12);setTimeout(()=>{const logs=[];state.players.filter(p=>p.action.tactic!=='feint').forEach(p=>p.node=p.action.move);const boost=state.rule.id==='bloodMoon'?1:0;for(const p of state.players){const a=p.action;if(a.tactic==='strike'&&state.rule.id!=='peace'){const ts=state.players.filter(x=>x.id!==p.id&&x.node===p.node&&x.hp>0),t=ts.find(x=>x.id===a.target)||ts[0];if(t){damage(t,2+boost,logs);logs.push(`${p.name} の斬撃 → ${t.name}`)}}}for(const p of state.players){if(p.action.tactic==='burst'&&state.rule.id!=='peace'){const ts=state.players.filter(x=>x.id!==p.id&&x.node===p.node&&x.hp>0);ts.forEach(t=>damage(t,1+boost,logs));if(ts.length)logs.push(`${p.name} が爆発！ ${ts.length}人を巻き込んだ`)}}state.players.filter(p=>p.action.tactic==='feint').forEach(p=>{p.node=p.action.move;logs.push(`${p.name} はフェイントで滑り込んだ`)});for(const p of state.players)if(p.action.tactic==='snatch'){const ts=state.players.filter(x=>x.id!==p.id&&x.node===p.node&&x.score>0),t=ts.find(x=>x.id===p.action.target)||ts.sort((x,y)=>y.score-x.score)[0];if(t){t.score--;p.score++;logs.push(`${p.name} が ${t.name} からGLORYを強奪`)}}const crown=state.players.filter(p=>p.node===0&&p.hp>0);crown.forEach(p=>{const g=(crown.length===1?3:1)*(state.rule.id==='doubleCrown'?2:1);p.score+=g;logs.push(`${p.name} が王冠の間で +${g}`)});state.players.filter(p=>p.node===state.spotlight&&p.hp>0).forEach(p=>{const g=state.rule.id==='festival'?3:1;p.score+=g;logs.push(`${p.name} が注目エリアで +${g}`)});state.players.forEach(p=>{if(p.hp<=0){p.score=Math.max(0,p.score-1);logs.push(`${p.name} は吹き飛ばされた`)}});const leader=[...state.players].sort((a,b)=>b.score-a.score)[0];Object.entries(state.predictions).forEach(([sid,pid])=>{const s=state.spectators.find(x=>x.id===sid);if(s&&pid===leader?.id)s.hype=(s.hype||0)+2});state.log=logs.slice(-3).join(' ／ ')||'静かな読み合いになった';sync();setTimeout(nextRound,3200)},1200)}
function nextRound(){if(!isHost)return;const w=[...state.players].sort((a,b)=>b.score-a.score)[0];if(state.round>=state.maxRounds||w.score>=state.winScore){state.phase='result';sync();return}state.round++;state.phase='choose';const t={};Object.values(state.votes).forEach(v=>t[v]=(t[v]||0)+1);const win=Object.entries(t).sort((a,b)=>b[1]-a[1])[0]?.[0];state.rule=rules.find(r=>r.id===win)||pick(state.nextRuleOptions)||rules[0];state.spotlight=7+Math.floor(Math.random()*6);resetRound();sync();startClock()}
function render(){if(!state)return;if(state.phase==='lobby'){show('lobby');renderLobby()}else if(state.phase==='result'){show('result');renderResult()}else{show('game');renderGame();startClock()}}
function renderLobby(){$('#roomCodeDisplay').textContent=room;$('#lobbyCount').textContent=`${state.players.length} / ${state.maxPlayers}`;$('#audienceLobbyCount').textContent=state.spectators.length;$('#startGameBtn').disabled=state.players.length<2;let h='';for(let i=0;i<state.maxPlayers;i++){const p=state.players[i];h+=p?`<div class="lobby-player ${p.host?'host':''}"><div class="avatar" style="background:${p.color}22;color:${p.color}">${esc(p.name.slice(0,2))}</div><strong>${esc(p.name)}</strong><small>${p.bot?'CPU':'接続済み'}</small></div>`:'<div class="lobby-player empty">空き枠</div>'}$('#playerLobbyList').innerHTML=h}
function renderGame(){$('#roundDisplay').textContent=`${state.round} / ${state.maxRounds}`;$('#ruleIcon').textContent=state.rule.icon;$('#ruleName').textContent=state.rule.name;$('#eventTicker span').textContent=state.log;const p=state.players.find(x=>x.id===me.id),spec=!p;$('#playerControls').classList.toggle('hidden',spec);$('#spectatorControls').classList.toggle('hidden',!spec);renderScore();renderArena();p?renderActions(p):renderSpectator();$('#phaseOverlay').classList.toggle('hidden',state.phase!=='reveal')}
function renderScore(){const s=[...state.players].sort((a,b)=>b.score-a.score||b.hp-a.hp);$('#scoreboard').innerHTML=s.map((p,i)=>`<div class="score-row ${p.id===me.id?'me':''}"><span class="score-rank">${i+1}</span><span class="score-avatar" style="background:${p.color}22;color:${p.color}">${esc(p.name.slice(0,2))}</span><div class="score-info"><strong>${esc(p.name)}</strong><div class="hp-bar"><i style="width:${clamp(p.hp,0,5)/5*100}%"></i></div></div><span class="score-points">${p.score}👑</span></div>`).join('')}
function renderActions(p){const ch=[p.node,...nodes[p.node].adj];$('#moveChoices').innerHTML=ch.map(n=>`<button class="choice-btn ${selectedMove===n?'active':''}" data-move="${n}" ${p.locked?'disabled':''}>${n===p.node?'待機':esc(nodes[n].n)}</button>`).join('');$('#tacticChoices').innerHTML=Object.entries(tactics).map(([k,t])=>`<button class="tactic-choice ${selectedTactic===k?'active':''}" data-tactic="${k}" ${p.locked?'disabled':''}><span>${t.icon}</span><div><strong>${t.name}</strong><small>${t.desc}</small></div></button>`).join('');$$('[data-move]').forEach(b=>b.onclick=()=>{selectedMove=+b.dataset.move;renderActions(p)});$$('[data-tactic]').forEach(b=>b.onclick=()=>{selectedTactic=b.dataset.tactic;renderActions(p)});const needs=['strike','snatch'].includes(selectedTactic);$('#targetBox').classList.toggle('hidden',!needs);if(needs){$('#targetSelect').innerHTML='<option value="">自動選択</option>'+state.players.filter(x=>x.id!==p.id).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('#targetSelect').onchange=e=>selectedTarget=e.target.value}$('#lockActionBtn').disabled=p.locked||selectedMove===null||!selectedTactic;$('#lockActionBtn').classList.toggle('hidden',p.locked);$('#unlockActionBtn').classList.toggle('hidden',!p.locked);$('#lockStatus').textContent=p.locked?'確定済み':'未確定'}
function renderSpectator(){const s=state.spectators.find(x=>x.id===me.id);$('#spectatorScore').textContent=`${s?.hype||0} HYPE`;$('#ruleVoteChoices').innerHTML=state.nextRuleOptions.map(r=>`<button class="vote-btn ${state.votes[me.id]===r.id?'active':''}" data-vote="${r.id}"><b>${r.icon}</b><span><strong>${r.name}</strong><small>${r.d}</small></span></button>`).join('');$('#predictionChoices').innerHTML=[...state.players].sort((a,b)=>b.score-a.score).map(p=>`<button class="prediction-btn ${state.predictions[me.id]===p.id?'active':''}" data-predict="${p.id}"><span style="color:${p.color}">●</span>${esc(p.name)} — ${p.score}点</button>`).join('');$$('[data-vote]').forEach(b=>b.onclick=()=>emit({type:'vote',id:me.id,rule:b.dataset.vote}));$$('[data-predict]').forEach(b=>b.onclick=()=>emit({type:'predict',id:me.id,player:b.dataset.predict}))}
function renderArena(){const c=$('#arenaCanvas'),x=c.getContext('2d'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;x.scale(d,d);const w=r.width,h=r.height;x.clearRect(0,0,w,h);x.lineWidth=2;x.strokeStyle='rgba(255,255,255,.10)';for(const n of nodes)for(const a of n.adj)if(a>n.id){x.beginPath();x.moveTo(n.x*w,n.y*h);x.lineTo(nodes[a].x*w,nodes[a].y*h);x.stroke()}for(const n of nodes){const px=n.x*w,py=n.y*h,rad=n.id===0?45:28;x.beginPath();x.arc(px,py,rad,0,Math.PI*2);x.fillStyle=n.id===0?'rgba(255,209,102,.15)':n.id===state.spotlight?'rgba(255,79,154,.16)':'rgba(255,255,255,.055)';x.fill();x.strokeStyle=n.id===0?'rgba(255,209,102,.8)':n.id===state.spotlight?'rgba(255,79,154,.8)':'rgba(255,255,255,.14)';x.stroke();x.textAlign='center';x.fillStyle='#eee';x.font=`700 ${n.id===0?12:9}px Inter`;x.fillText(n.id===0?'♛ 王冠の間':n.n,px,py+4)}const g={};state.players.forEach(p=>(g[p.node]??=[]).push(p));Object.entries(g).forEach(([ni,ps])=>{const n=nodes[ni];ps.forEach((p,i)=>{const a=i/ps.length*Math.PI*2-Math.PI/2,rr=ps.length===1?0:36,px=n.x*w+Math.cos(a)*rr,py=n.y*h+Math.sin(a)*rr;x.beginPath();x.arc(px,py,15,0,Math.PI*2);x.fillStyle=p.color;x.shadowBlur=14;x.shadowColor=p.color;x.fill();x.shadowBlur=0;x.strokeStyle='#111';x.lineWidth=3;x.stroke();x.fillStyle='#111';x.font='900 8px Inter';x.fillText(p.name.slice(0,2),px,py+3);if(state.phase==='reveal'){x.font='18px serif';x.fillText(tactics[p.action?.tactic]?.icon||'',px,py-20)}})})}
function renderResult(){const s=[...state.players].sort((a,b)=>b.score-a.score||b.hp-a.hp),w=s[0];$('#winnerName').textContent=w?.name||'WINNER';$('#winnerSub').textContent=`${w?.score||0} GLORYで王冠を獲得`;$('#finalRanking').innerHTML=s.map((p,i)=>`<div class="final-row"><strong>${i+1}</strong><span class="score-avatar" style="background:${p.color}22;color:${p.color}">${esc(p.name.slice(0,2))}</span><span>${esc(p.name)}</span><b>${p.score} 👑</b></div>`).join('')}
function emit(m){if(isHost)hostMessage({peer:'host',open:true,send(){}},m);else send(hostConn,m)}function floatReact(e){const d=document.createElement('span');d.className='floating-reaction';d.textContent=e;d.style.left=(5+Math.random()*90)+'%';$('#reactionLayer').append(d);setTimeout(()=>d.remove(),3000)}
function drawQR(text){const c=$('#qrCanvas'),x=c.getContext('2d'),N=29,s=c.width/N;let seed=[...text].reduce((a,ch)=>(a*31+ch.charCodeAt(0))>>>0,7);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const f=(ox,oy)=>{for(let y=0;y<7;y++)for(let z=0;z<7;z++){const on=z===0||y===0||z===6||y===6||(z>=2&&z<=4&&y>=2&&y<=4);x.fillStyle=on?'#090910':'#fff';x.fillRect((ox+z)*s,(oy+y)*s,Math.ceil(s),Math.ceil(s))}};for(let y=0;y<N;y++)for(let z=0;z<N;z++){seed=(seed*1664525+1013904223)>>>0;if(seed&1){x.fillStyle='#090910';x.fillRect(z*s,y*s,Math.ceil(s),Math.ceil(s))}}f(1,1);f(N-8,1);f(1,N-8)}
function rematch(){if(!isHost)return;state.players.forEach(p=>{p.hp=5;p.score=0;p.node=Math.floor(Math.random()*6)+1});state.round=1;state.phase='choose';state.rule=rules[0];resetRound();sync();startClock()}
$$('[data-entry-tab]').forEach(b=>b.onclick=()=>{$$('[data-entry-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#hostForm').classList.toggle('active',b.dataset.entryTab==='host');$('#joinForm').classList.toggle('active',b.dataset.entryTab==='join')});$$('[data-role]').forEach(b=>b.onclick=()=>$$('[data-role]').forEach(x=>x.classList.toggle('active',x===b)));$('#createRoomBtn').onclick=createRoom;$('#joinRoomBtn').onclick=joinRoom;$('#addBotBtn').onclick=addBot;$('#startGameBtn').onclick=startGame;$('#copyInviteBtn').onclick=$('#roomCodeDisplay').onclick=()=>{navigator.clipboard?.writeText(location.origin+location.pathname+'?room='+room);toast('招待URLをコピーしたよ')};$('#lockActionBtn').onclick=()=>{const a={move:selectedMove,tactic:selectedTactic,target:selectedTarget};if(isHost){const p=state.players.find(x=>x.id===me.id);p.action=a;p.locked=true;sync();checkReady()}else emit({type:'action',id:me.id,action:a})};$('#unlockActionBtn').onclick=()=>{if(isHost){const p=state.players.find(x=>x.id===me.id);p.action=null;p.locked=false;sync()}else emit({type:'unlock',id:me.id})};$('#reactionButtons').onclick=e=>{const b=e.target.closest('button');if(!b||Date.now()-lastReact<600)return;lastReact=Date.now();const m={type:'react',emoji:b.textContent};if(isHost){broadcast(m);floatReact(m.emoji)}else emit(m)};$('#soundBtn').onclick=()=>{audio=!audio;$('#soundBtn').textContent=audio?'🔊':'🔇'};$('#helpBtn').onclick=()=>$('#helpDialog').showModal();$('#closeHelpBtn').onclick=()=>$('#helpDialog').close();$('#rematchBtn').onclick=rematch;$('#backLobbyBtn').onclick=()=>isHost?(state.phase='lobby',state.round=0,sync()):show('lobby');$('#brandBtn').onclick=()=>location.href=location.pathname;addEventListener('resize',()=>state&&state.phase!=='lobby'&&renderArena());const q=new URLSearchParams(location.search).get('room');if(q){$('.tab[data-entry-tab="join"]').click();$('#roomCodeInput').value=q.toUpperCase()}